spring:
  application:
    name: PaperSpring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Paper?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd
#    password: dlxogud963
  jpa:
    show-sql: true # DDL(create, alter, drop) ??? DB? ?? ??? ??? ? ??.
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 20MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량