spring:
  application:
    name: PaperSpring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Paper?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd
  jpa:
    show-sql: true # DDL(create, alter, drop) ??? DB? ?? ??? ??? ? ??.
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true